// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// knn_vote
Rcpp::NumericVector knn_vote(const arma::rowvec& V, const arma::mat& M, const int steps);
RcppExport SEXP _scArch_knn_vote(SEXP VSEXP, SEXP MSEXP, SEXP stepsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::rowvec& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const int >::type steps(stepsSEXP);
    rcpp_result_gen = Rcpp::wrap(knn_vote(V, M, steps));
    return rcpp_result_gen;
END_RCPP
}
// MeanShift1
Rcpp::NumericVector MeanShift1(const arma::rowvec& V, const arma::mat& M, const arma::mat& N, const int steps);
RcppExport SEXP _scArch_MeanShift1(SEXP VSEXP, SEXP MSEXP, SEXP NSEXP, SEXP stepsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::rowvec& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type N(NSEXP);
    Rcpp::traits::input_parameter< const int >::type steps(stepsSEXP);
    rcpp_result_gen = Rcpp::wrap(MeanShift1(V, M, N, steps));
    return rcpp_result_gen;
END_RCPP
}
// subcluster_stable
double subcluster_stable(const arma::uvec& ind, const arma::mat& M, const arma::mat& N, const int steps);
RcppExport SEXP _scArch_subcluster_stable(SEXP indSEXP, SEXP MSEXP, SEXP NSEXP, SEXP stepsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::uvec& >::type ind(indSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type N(NSEXP);
    Rcpp::traits::input_parameter< const int >::type steps(stepsSEXP);
    rcpp_result_gen = Rcpp::wrap(subcluster_stable(ind, M, N, steps));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_scArch_knn_vote", (DL_FUNC) &_scArch_knn_vote, 3},
    {"_scArch_MeanShift1", (DL_FUNC) &_scArch_MeanShift1, 4},
    {"_scArch_subcluster_stable", (DL_FUNC) &_scArch_subcluster_stable, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_scArch(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
